function tab = read_table(fid,nlines)

tab = struct('image',{},'ier',{},'scale',{},'nbkg',{},'novl',{},...
    'newald',{},'nstrong',{},'nreg',{},'sigmab',{},'sigmar',{});
fn = fieldnames(tab);
for j=1:nlines
    if feof(fid)
        break;
    end
    newline = fgetl(fid);
    tab_tmp = regexp(newline,...
        ['^\s*(?<image>\d+)',...
        '\s+(?<ier>-*\d+)',...
        '\s+(?<scale>[\d\.]+)',...
        '\s+(?<nbkg>\d+)',...
        '\s+(?<novl>\d+)',...
        '\s+(?<newald>\d+)',...
        '\s+(?<nstrong>\d+)',...
        '\s+(?<nreg>\d+)',...
        '\s+(?<sigmab>[\d\.]+)',...
        '\s+(?<sigmar>[\d\.]+)',...
        '\s*$'],'names');
    try
        for k=1:length(fn)
            tab(j).(fn{k}) = str2num(tab_tmp.(fn{k}));
        end
    catch
        warning('failed to load some part of this table');
        disp(struct2table(tab));
    end
end

end
