function tf = write_xparm(xParm,fileName)
% see load_xparm.m
fid = fopen(fileName,'w');
tf = false;

try
    fprintf(fid,'%s\n',xParm.header_text);
    fprintf(fid,'%6d     %9.4f %9.4f %9.6f %9.6f %9.6f\n',...
        xParm.starting_frame,...
        xParm.starting_angle,...
        xParm.oscillation_range,...
        xParm.rotation_axis);
    fprintf(fid,' %14.6f %14.6f %14.6f %14.6f\n',...
        xParm.lambda,xParm.incident_wavevector);
    fprintf(fid,'%6d %11.4f %11.4f %11.4f %7.3f %7.3f %7.3f\n',...
        xParm.space_group_number,...
        xParm.a,xParm.b,xParm.c,xParm.alpha,xParm.beta,xParm.gamma);
    fprintf(fid,' %14.6f %14.6f %14.6f\n',...
        xParm.a_axis,xParm.b_axis,xParm.c_axis);
    fprintf(fid,' %9d %9d %9d %11.6f %11.6f\n',...
        xParm.detector.nseg,...
        xParm.detector.nx,...
        xParm.detector.ny,...
        xParm.detector.qx,...
        xParm.detector.qy);
    fprintf(fid,' %14.6f %14.6f %14.6f\n',...
        xParm.detector.orgx,xParm.detector.orgy,xParm.detector.f);
    fprintf(fid,' %14.6f %14.6f %14.6f\n',...
        xParm.detector.ed(:,1),xParm.detector.ed(:,2),xParm.detector.ed(:,3));
    
    for j=1:xParm.detector.nseg
        fprintf(fid,' %9d %9d %9d %9d %9d\n',...
            xParm.detector.segments(j).iseg,...
            xParm.detector.segments(j).x1,...
            xParm.detector.segments(j).x2,...
            xParm.detector.segments(j).y1,...
            xParm.detector.segments(j).y2);
        fprintf(fid,' %7.2f %7.2f %7.2f %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f\n',...
            xParm.detector.segments(j).orgxs,...
            xParm.detector.segments(j).orgys,...
            xParm.detector.segments(j).fs,...
            xParm.detector.segments(j).eds(:,1),...
            xParm.detector.segments(j).eds(:,2));
    end
catch ME
    fclose(fid);
    rethrow(ME);
end
tf = true;

end