classdef Element
    %ELEMENT - look up mass and vdw radius parameters for the elements
    
    properties(SetAccess = immutable)
        atomicSymbol
        atomicNumber
        atomicMass
        vdwRadius
    end
    properties(Dependent = true)
        ScatteringFactor
        AbsorptionCoefficient
    end
    properties(Constant = true, Access = private)
        % the following data tables were generated by private/parse_atomic_mass_data.m
        atomicMasses = [1.0079 4.0026 6.94 9.0122 10.811 12.0107 14.0067 15.9994 18.9984 20.18 22.9898 24.3051 26.9815 28.0855 30.9738 32.0648 35.4529 39.9478 39.0983 40.078 44.9559 47.8667 50.9415 51.9961 54.938 55.8451 58.9332 58.6933 63.546 65.3778 69.7231 72.6276 74.9216 78.9594 79.9035 83.798 85.4677 87.6166 88.9058 91.2236 92.9064 95.9598 98 101.0649 102.9055 106.4153 107.8681 112.4116 114.8181 118.7101 121.7598 127.6031 126.9045 131.2928 132.9055 137.3269 138.9055 140.1157 140.9077 144.2416 145 150.3664 151.9644 157.2521 158.9254 162.4995 164.9303 167.2591 168.9342 173.0542 174.9668 178.485 180.9479 183.8418 186.2067 190.2249 192.2161 195.0845 196.9666 200.5992 204.3834 207.2169 208.9804 209 210 222 223 226 227 232.0381 231.0359 238.0289 237 244 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN];
        atomicSymbols = {'H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'};
        vdwRadii = [1.2 1.4 1.82 0.63 1.75 1.775 1.5 1.45 1.47 1.54 2.27 1.73 1.5 2.1 1.9 1.8 1.75 1.88 2.75 1.95 1.32 1.95 1.06 1.13 1.19 1.26 1.13 1.63 1.4 1.39 1.87 1.48 0.83 1.9 1.85 2.02 2.65 2.02 1.61 1.42 1.33 1.75 2 1.2 1.22 1.63 1.72 1.58 1.93 2.17 1.12 1.26 1.98 2.16 3.01 2.41 1.83 1.86 1.62 1.79 1.76 1.74 1.96 1.69 1.66 1.63 1.61 1.59 1.57 1.54 1.53 1.4 1.22 1.26 1.3 1.58 1.22 1.72 1.66 1.55 1.96 2.02 1.73 1.21 1.12 2.3 3.24 2.57 2.12 1.84 1.6 1.75 1.71 1.67 1.66 1.65 1.64 1.63 1.62 1.61 1.6 1.59 1.58 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN];
    end
    methods
        function obj = Element(arg)
            %ELEMENT Construct an instance of this class
            nAtoms = length(obj.atomicMasses);
            if nargin>0 && isnumeric(arg) && length(arg)==1
                assert(arg <= nAtoms,'atomic number not recognized');
                obj.atomicNumber = arg;
            elseif nargin>0 && ischar(arg)
                % make case-insensitive (changed july 12, 2018)
                [ia,ib] = ismember(lower(arg),lower(obj.atomicSymbols));
                assert(ia,'atomic symbol not recognized');
                obj.atomicNumber = ib;
            else
                error('arguments not recognized');
            end
            obj.atomicSymbol = obj.atomicSymbols{obj.atomicNumber};
            obj.atomicMass = obj.atomicMasses(obj.atomicNumber);
            obj.vdwRadius = obj.vdwRadii(obj.atomicNumber);
        end
        function val = get.ScatteringFactor(obj)
            val = model.atom.ScatteringFactor(obj.atomicSymbol);
        end
        function val = get.AbsorptionCoefficient(obj)
            val = model.atom.AbsorptionCoefficient(obj.atomicSymbol);
        end
    end
end

