function kwds = get_cif_binary_keywords()

kwds = struct(...
    'Content_Type',struct('pattern','Content-Type:\s+(.*);','type','str'),...
    'conversions',struct('pattern','conversions="(.*)"','type','str'),...
    'Content_Transfer_Encoding',struct('pattern','Content-Transfer-Encoding:\s+(.*)','type','str'),...
    'X_Binary_Size',struct('pattern','X-Binary-Size:\s+(\d+)','type','int'),...
    'X_Binary_ID',struct('pattern','X-Binary-ID:\s+(\d+)','type','int'),...
    'X_Binary_Element_Type',struct('pattern','X-Binary-Element-Type:\s+"(.*)"','type','str'),...
    'X_Binary_Element_Byte_Order',struct('pattern','X-Binary-Element-Byte-Order:\s+(.*)','type','str'),...
    'Content_MD5',struct('pattern','Content-MD5:\s+(.*)','type','str'),...
    'X_Binary_Number_of_Elements',struct('pattern','X-Binary-Number-of-Elements:\s+(\d+)','type','int'),...
    'X_Binary_Size_Fastest_Dimension',struct('pattern','X-Binary-Size-Fastest-Dimension:\s+(\d+)','type','int'),...
    'X_Binary_Size_Second_Dimension',struct('pattern','X-Binary-Size-Second-Dimension:\s+(\d+)','type','int'),...
    'X_Binary_Size_Padding',struct('pattern','X-Binary-Size-Padding:\s+(\d+)','type','int')...
    );

end