function kwds = get_non_optional_keywords()

kwds = struct(...
    'Detector_identifier', struct('pattern','Detector (.*)',    'value_indices', 'tokens','type', 'str'),...
    'Pixel_size',          struct('pattern','Pixel_size',       'value_indices', [1, 4], 'type', 'float'),...
    'Silicon',             struct('pattern','Silicon',          'value_indices', [3],    'type', 'float'),...
    'Exposure_time',       struct('pattern','Exposure_time',    'value_indices', [1],    'type', 'float'),...
    'Exposure_period',     struct('pattern','Exposure_period',  'value_indices', [1],    'type', 'float'),...
    'Tau',                 struct('pattern','Tau',              'value_indices', [1],    'type', 'float'),...
    'Count_cutoff',        struct('pattern','Count_cutoff',     'value_indices', [1],    'type', 'int'),...
    'Threshold_setting',   struct('pattern','Threshold_setting','value_indices', [1],    'type', 'float'),...
    'Gain_setting',        struct('pattern','Gain_setting' ,    'value_indices', [1, 2], 'type', 'str'),...
    'N_excluded_pixels',   struct('pattern','N_excluded_pixels','value_indices', [1],    'type', 'int'),...
    'Excluded_pixels',     struct('pattern','Excluded_pixels',  'value_indices', [1],    'type', 'str'),...
    'Flat_field',          struct('pattern','Flat_field',       'value_indices', [1],    'type', 'str'),...
    'Trim_file',           struct('pattern','Trim_file',        'value_indices', [1],    'type', 'str'),...
    'Image_path',          struct('pattern','Image_path',       'value_indices', [1],    'type', 'str')...
    );

end