function kwds = get_optional_keywords()
kwds = struct(...
    'Wavelength',           struct('pattern','Wavelength',      'value_indices', [1],   'type', 'float'),...
    'Energy_range',         struct('pattern','Energy_range',    'value_indices', [1, 2],'type', 'float'),...
    'Detector_distance',    struct('pattern','Detector_distance','value_indices', [1],  'type', 'float'),...
    'Detector_Voffset',     struct('pattern','Detector_Voffset','value_indices', [1],   'type', 'float'),...
    'Beam_xy',              struct('pattern','Beam_xy',         'value_indices', [1, 2],'type', 'float'),...
    'Beam_x',               struct('pattern','Beam_xy',         'value_indices', [1],   'type', 'float'),...
    'Beam_y',               struct('pattern','Beam_xy',         'value_indices', [2],   'type', 'float'),...
    'Flux',                 struct('pattern','Flux',            'value_indices', [1],   'type', 'str'),...
    'Filter_transmission',  struct('pattern','Filter_transmission','value_indices',[1], 'type', 'float'),...
    'Start_angle',          struct('pattern','Start_angle',     'value_indices', [1],   'type', 'float'),...
    'Angle_increment',      struct('pattern','Angle_increment', 'value_indices', [1],   'type', 'float'),...
    'Detector_2theta',      struct('pattern','Detector_2theta', 'value_indices', [1],   'type', 'float'),...
    'Polarization',         struct('pattern','Polarization',    'value_indices', [1],   'type', 'float'),...
    'Alpha',                struct('pattern','Alpha',           'value_indices', [1],   'type', 'float'),...
    'Kappa',                struct('pattern','Kappa',           'value_indices', [1],   'type', 'float'),...
    'Phi',                  struct('pattern','Phi',             'value_indices', [1],   'type', 'float'),...
    'Phi_increment',        struct('pattern','Phi_increment',   'value_indices', [1],   'type', 'float'),...
    'Chi',                  struct('pattern','Chi',             'value_indices', [1],   'type', 'float'),...
    'Chi_increment',        struct('pattern','Chi_increment',   'value_indices', [1],   'type', 'float'),...
    'Oscillation_axis',     struct('pattern','Oscillation_axis (.*)','value_indices', 'tokens',    'type', 'str'),...
    'N_oscillations',       struct('pattern','N_oscillations',  'value_indices', [1],   'type', 'int'),...
    'Start_position',       struct('pattern','Start_position',  'value_indices', [1],   'type', 'float'),...
    'Position_increment',   struct('pattern','Position_increment','value_indices', [1], 'type', 'float'),...
    'Shutter_time',         struct('pattern','Shutter_time',    'value_indices', [1],   'type', 'float')...
    );
end