function out = xds_inp_translate(varargin)

xds_imp_commands = list_xds_inp_commands();

if isempty(varargin)

    xds_commands = struct();
    for j=1:length(xds_imp_commands)
        xds_commands.(repfun(xds_imp_commands{j})) = xds_imp_commands{j};
    end
    out = xds_commands;
else
    if length(varargin)==1
        cmd = varargin{1};
        if ~any(strcmp(cmd,xds_imp_commands))
            warning('did not recognize command %s',cmd);
        end
        out = repfun(cmd);
    else
        out = varargin;
        for j=1:length(varargin)
            cmd = varargin{1};
            if ~any(strcmp(cmd,xds_imp_commands))
                warning('did not recognize command %s',cmd);
            end
            out{j} = repfun(cmd);
        end
    end
    
end
end

function repstr = repfun(inpstr)
repstr = inpstr;
repstr = regexprep(repstr,'\)','');
repstr = regexprep(repstr,'\(','_');
repstr = regexprep(repstr,'\/','_');
repstr = regexprep(repstr,'\''','');
repstr = regexprep(repstr,'\.','');
repstr = regexprep(repstr,'\-','_');
repstr = lower(repstr);
end

function xds_imp_commands = list_xds_inp_commands()

xds_imp_commands = ...
    {'JOB',...
    'MAXIMUM_NUMBER_OF_JOBS',...
    'MAXIMUM_NUMBER_OF_PROCESSORS',...
    'SECONDS',...
    'TEST',...
    'DETECTOR',...
    'NX',...
    'NY',...
    'QX',...
    'QY',...
    'OVERLOAD',...
    'MINIMUM_VALID_PIXEL_VALUE',...
    'TRUSTED_REGION',...
    'UNTRUSTED_RECTANGLE',...
    'UNTRUSTED_ELLIPSE',...
    'UNTRUSTED_QUADRILATERAL',...
    'SILICON',...
    'SENSOR_THICKNESS' ,...
    'GAIN', ... % added December 15, 2016: added to XDS Nov 2016?
    'ROFF',...
    'TOFF',...
    'STOE_CALIBRATION_PARAMETERS',...
    'BRASS_PLATE_IMAGE',...
    'HOLE_DISTANCE',...
    'MXHOLE',...
    'MNHOLE',...
    'X-GEO_CORR',...
    'Y-GEO_CORR',...
    'DARK_CURRENT_IMAGE',...
    'OFFSET' ,...
    'VALUE_RANGE_FOR_TRUSTED_DETECTOR_PIXELS',...
    'INCLUDE_RESOLUTION_RANGE',...
    'EXCLUDE_RESOLUTION_RANGE',...
    'MINIMUM_ZETA' ,...
    'DIRECTION_OF_DETECTOR_X-AXIS',...
    'DIRECTION_OF_DETECTOR_Y-AXIS',...
    'ORGX',...
    'ORGY',...
    'DETECTOR_DISTANCE',...
    'SEGMENT',...
    'REFINE_SEGMENT',...
    'DIRECTION_OF_SEGMENT_X-AXIS',...
    'DIRECTION_OF_SEGMENT_Y-AXIS',...
    'SEGMENT_ORGX',...
    'SEGMENT_ORGY',...
    'SEGMENT_DISTANCE' ,...
    'NAME_TEMPLATE_OF_DATA_FRAMES',...
    'DATA_RANGE',...
    'EXCLUDE_DATA_RANGE',... % added October 4 2017 (has been in XDS how long?)
    'SPOT_RANGE',...
    'BACKGROUND_RANGE',...
    'MINIMUM_FRACTION_OF_BACKGROUND_REGION' ,...
    'ROTATION_AXIS',...
    'OSCILLATION_RANGE' ,...
    'X-RAY_WAVELENGTH',...
    'INCIDENT_BEAM_DIRECTION',...
    'FRACTION_OF_POLARIZATION',...
    'POLARIZATION_PLANE_NORMAL',...
    'AIR' ,...
    'SPACE_GROUP_NUMBER',...
    'UNIT_CELL_CONSTANTS',...
    'UNIT_CELL_A-AXIS',...
    'UNIT_CELL_B-AXIS',...
    'UNIT_CELL_C-AXIS',...
    'REIDX',...
    'FRIEDEL''S_LAW',...
    'STARTING_ANGLE',...
    'STARTING_FRAME',...
    'STARTING_ANGLES_OF_SPINDLE_ROTATION',...
    'TOTAL_SPINDLE_ROTATION_RANGES',...
    'RESOLUTION_SHELLS',...
    'REFERENCE_DATA_SET',...
    'MAX_CELL_AXIS_ERROR',...
    'MAX_CELL_ANGLE_ERROR',...
    'TEST_RESOLUTION_RANGE',...
    'MIN_RFL_Rmeas',...
    'MAX_FAC_Rmeas' ,...
    'NBX',...
    'NBY',...
    'BACKGROUND_PIXEL',...
    'STRONG_PIXEL',...
    'MAXIMUM_NUMBER_OF_STRONG_PIXELS',...
    'MINIMUM_NUMBER_OF_PIXELS_IN_A_SPOT',...
    'SPOT_MAXIMUM-CENTROID',...
    'SIGNAL_PIXEL' ,...
    'INDEX_ORIGIN',...
    'INDEX_ERROR',...
    'INDEX_MAGNITUDE',...
    'INDEX_QUALITY',...
    'SEPMIN',...
    'CLUSTER_RADIUS',...
    'MAXIMUM_ERROR_OF_SPOT_POSITION',...
    'MAXIMUM_ERROR_OF_SPINDLE_POSITION',...
    'MINIMUM_FRACTION_OF_INDEXED_SPOTS' ,...
    'REFINE(IDXREF)',...
    'REFINE(INTEGRATE)',...
    'REFINE(CORRECT)',...
    'DEFAULT_REFINE_SEGMENT',...
    'MINIMUM_NUMBER_OF_REFLECTIONS/SEGMENT' ,...
    'REFLECTING_RANGE',...
    'REFLECTING_RANGE_E.S.D.',...
    'BEAM_DIVERGENCE',...
    'BEAM_DIVERGENCE_E.S.D.',...
    'NUMBER_OF_PROFILE_GRID_POINTS_ALONG_ALPHA/BETA',...
    'NUMBER_OF_PROFILE_GRID_POINTS_ALONG_GAMMA',...
    'CUT',...
    'DELPHI',...
    'MINPK',...
    'WFAC1',...
    'PROFILE_FITTING' ,...
    'STRICT_ABSORPTION_CORRECTION',...
    'PATCH_SHUTTER_PROBLEM',...
    'CORRECTIONS',...
    'MINIMUM_I/SIGMA',...
    'NBATCH',...
    'REFLECTIONS/CORRECTION_FACTOR',...
    'REJECT_ALIEN',...
    'DATA_RANGE_FIXED_SCALE_FACTOR' };

end